<?php

namespace port\portfolioBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * ProjetsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjetsRepository extends EntityRepository
{
	public function getProjetsFac()
    {

  		$query = $this->createQueryBuilder('a')
  					  ->where('a.type = :type')
  					  ->setParameter('type', 'fac')
                	  ->orderBy('a.date', 'ASC')
        			  ->getQuery();

    	return new Paginator($query);
    }

    public function getProjetsPerso()
    {

  		$query = $this->createQueryBuilder('a')
  					  ->where('a.type = :type')
  					  ->setParameter('type', 'perso')
                 	  ->orderBy('a.date', 'ASC')
        			  ->getQuery();

  		return new Paginator($query);
    }

    public function getIdee()
    {

  		$query = $this->createQueryBuilder('a')
  					  ->where('a.type = :type')
  					  ->setParameter('type', 'futur')
        			  ->getQuery();

  		return new Paginator($query);
    }
}
