parameters:
#    portportfolio.example.class: port\portfolioBundle\Example

services:
#    portportfolio.example:
#        class: %portportfolio.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
